package com.dmjsistemas.model;
// Generated 13/07/2022 10:51:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Autos generated by hbm2java
 */
public class Autos  implements java.io.Serializable {


     private int idauto;
     private String nombreVehiculo;
     private String noSerie;
     private Integer anio;
     private String noPlacas;
     private BigDecimal valor;
     private BigDecimal deducible;
     private BigDecimal noDeducible;
     private Integer porcentajeDeducible;
     private Integer porcentajeNoDeducible;
     private String departamento;
     private Set gastos = new HashSet(0);

    public Autos() {
    }

	
    public Autos(int idauto) {
        this.idauto = idauto;
    }
    public Autos(int idauto, String nombreVehiculo, String noSerie, Integer anio, String noPlacas, BigDecimal valor, BigDecimal deducible, BigDecimal noDeducible, Integer porcentajeDeducible, Integer porcentajeNoDeducible, String departamento, Set gastos) {
       this.idauto = idauto;
       this.nombreVehiculo = nombreVehiculo;
       this.noSerie = noSerie;
       this.anio = anio;
       this.noPlacas = noPlacas;
       this.valor = valor;
       this.deducible = deducible;
       this.noDeducible = noDeducible;
       this.porcentajeDeducible = porcentajeDeducible;
       this.porcentajeNoDeducible = porcentajeNoDeducible;
       this.departamento = departamento;
       this.gastos = gastos;
    }
   
    public int getIdauto() {
        return this.idauto;
    }
    
    public void setIdauto(int idauto) {
        this.idauto = idauto;
    }
    public String getNombreVehiculo() {
        return this.nombreVehiculo;
    }
    
    public void setNombreVehiculo(String nombreVehiculo) {
        this.nombreVehiculo = nombreVehiculo;
    }
    public String getNoSerie() {
        return this.noSerie;
    }
    
    public void setNoSerie(String noSerie) {
        this.noSerie = noSerie;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }
    public String getNoPlacas() {
        return this.noPlacas;
    }
    
    public void setNoPlacas(String noPlacas) {
        this.noPlacas = noPlacas;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public BigDecimal getDeducible() {
        return this.deducible;
    }
    
    public void setDeducible(BigDecimal deducible) {
        this.deducible = deducible;
    }
    public BigDecimal getNoDeducible() {
        return this.noDeducible;
    }
    
    public void setNoDeducible(BigDecimal noDeducible) {
        this.noDeducible = noDeducible;
    }
    public Integer getPorcentajeDeducible() {
        return this.porcentajeDeducible;
    }
    
    public void setPorcentajeDeducible(Integer porcentajeDeducible) {
        this.porcentajeDeducible = porcentajeDeducible;
    }
    public Integer getPorcentajeNoDeducible() {
        return this.porcentajeNoDeducible;
    }
    
    public void setPorcentajeNoDeducible(Integer porcentajeNoDeducible) {
        this.porcentajeNoDeducible = porcentajeNoDeducible;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public Set getGastos() {
        return this.gastos;
    }
    
    public void setGastos(Set gastos) {
        this.gastos = gastos;
    }




}


