package com.dmjsistemas.model;
// Generated 13/07/2022 10:51:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipos generated by hbm2java
 */
public class Tipos  implements java.io.Serializable {


     private int idtipo;
     private String tipoGasto;
     private Set gastos = new HashSet(0);

    public Tipos() {
    }

	
    public Tipos(int idtipo) {
        this.idtipo = idtipo;
    }
    public Tipos(int idtipo, String tipoGasto, Set gastos) {
       this.idtipo = idtipo;
       this.tipoGasto = tipoGasto;
       this.gastos = gastos;
    }
   
    public int getIdtipo() {
        return this.idtipo;
    }
    
    public void setIdtipo(int idtipo) {
        this.idtipo = idtipo;
    }
    public String getTipoGasto() {
        return this.tipoGasto;
    }
    
    public void setTipoGasto(String tipoGasto) {
        this.tipoGasto = tipoGasto;
    }
    public Set getGastos() {
        return this.gastos;
    }
    
    public void setGastos(Set gastos) {
        this.gastos = gastos;
    }




}


